In [12]:
!pip install -r requirements.txt

Requirement already satisfied: numpy==1.24.3 in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: scipy==1.10.1 in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (1.10.1)
Requirement already satisfied: scikit-learn==1.3.0 in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: threadpoolctl==3.1.0 in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: pandas in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 5)) (2.2.3)
Requirement already satisfied: sweetviz in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 6)) (2.3.1)
Requirement already satisfied: matplotlib in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 7)) (3.7.2)
Requirement already satisfied: seaborn in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 8)) (0.12.2)
Requirement already satisfied: statsmodels in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 9)) (0.14.0)
Requirement already satisfied: category_encoders in c:\users\store\anaconda3\lib\site-packages (from -r requirements.txt (line 11)) (2.6.3)

ERROR: Could not find a version that satisfies the requirement skopt (from versions: none)
ERROR: No matching distribution found for skopt

In [13]:
# For Data Manipulation
import pandas as pd
import numpy as np

# For Data Visualisation
import sweetviz as sv

In [14]:
# Loading in the Data
df = pd.read_csv("Data\MockDataSet1.csv")
df = df.drop(columns=['Unnamed: 0']) 
df

,QuoteRef,Channel,Product,Smoker,Joint?,Person1 Age,Term,TotalPremium,NBC,Sold,JF (Score),WGB (No. of other addresses held),X (Months same person on ER at current address),EF (No. of people not same surname at current address),NOB (Property group),URB (Income group),LSB (Regional banded house price band),BB (Number of CCJs),ND (Months since last CCJ)
0,QPCW-43,CTM,Level,Y,Y,38.0,20,36.22,1116.22,N,477,NaN,-999997.0,-999997.0,17,7,5.0,-999997.0,NaN
1,XXHO-52,CTM,Level accelerated,Y,N,47.0,10,29.36,673.04,N,562,3.0,-999997.0,3.0,9,8,4.0,0.0,-999997.0
2,KTGM-13,Direct,Decreasing with CI,N,Y,47.0,10,20.00,452.07,N,472,8.0,21.0,4.0,9,7,4.0,2.0,12.0
3,LKFU-15,MSM,Level with CI,Y,N,37.0,5,20.00,452.07,N,472,8.0,21.0,4.0,9,7,4.0,2.0,12.0
4,OZIK-66,Direct,Level with CI,N,Y,35.0,20,22.41,572.16,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753,GUZK-85,Direct,Level,Y,Y,41.0,5,17.07,477.05,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2754,GUZK-85,Direct,Level,Y,Y,41.0,5,17.07,477.05,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2755,ZEFY-74,CTM,Level accelerated,Y,N,49.0,30,62.69,1878.51,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2756,HLVT-14,CTM,Level with CI,N,N,47.0,10,62.69,1878.51,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2757,KGYU-95,MSM,Level,N,N,48.0,5,62.69,1878.51,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Running some quick summaries

In [15]:
# Checking counts and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2758 entries, 0 to 2757
Data columns (total 19 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   QuoteRef                                                2758 non-null   object
 1   Channel                                                 2758 non-null   object
 2   Product                                                 2758 non-null   object
 3   Smoker                                                  2757 non-null   object
 4   Joint?                                                  2758 non-null   object
 5   Person1 Age                                             2757 non-null   float64
 6   Term                                                    2758 non-null   int64
 7   TotalPremium                                            2758 non-null   float64
 8   NBC                                                     2758 non-null   float64
 9   Sold                                                    2758 non-null   object
 10  JF (Score)                                              2758 non-null   int64
 11  WGB (No. of other addresses held)                       1933 non-null   float64
 12  X (Months same person on ER at current address)         2043 non-null   float64
 13  EF (No. of people not same surname at current address)  2043 non-null   float64
 14  NOB (Property group)                                    2043 non-null   object
 15  URB (Income group)                                      2043 non-null   object
 16  LSB (Regional banded house price band)                  2043 non-null   float64
 17  BB (Number of CCJs)                                     2043 non-null   float64
 18  ND (Months since last CCJ)                              1933 non-null   float64
dtypes: float64(9), int64(2), object(8)
memory usage: 409.5+ KB

In [16]:
# Checking numerical summaries
df.describe()

,Person1 Age,Term,TotalPremium,NBC,JF (Score),WGB (No. of other addresses held),X (Months same person on ER at current address),EF (No. of people not same surname at current address),LSB (Regional banded house price band),BB (Number of CCJs),ND (Months since last CCJ)
count,2757.000000,2758.000000,2758.000000,2758.000000,2758.000000,1933.000000,2043.000000,2043.000000,2043.000000,2043.000000,1933.000000
mean,44.250635,20.685279,32.948535,819.074674,3003.419507,2.645111,-532526.341654,-53835.517376,-19572.171806,-53842.180127,-964817.452147
std,8.193590,8.924883,37.402838,1017.456197,4139.299434,2.307669,499083.755264,225762.598174,138583.057293,225761.008307,184283.979130
min,18.000000,5.000000,2.980000,0.000000,441.000000,0.000000,-999997.000000,-999997.000000,-999997.000000,-999997.000000,-999997.000000
25%,39.000000,15.000000,13.240000,307.057500,554.000000,1.000000,-999997.000000,3.000000,3.000000,0.000000,-999997.000000
50%,45.000000,20.000000,23.320000,526.095000,567.000000,2.000000,-999997.000000,5.000000,5.000000,0.000000,-999997.000000
75%,49.000000,30.000000,37.505000,935.327500,9999.000000,4.000000,21.500000,8.000000,7.000000,0.000000,-999997.000000
max,64.000000,40.000000,489.070000,13600.190000,9999.000000,12.000000,397.000000,55.000000,99.000000,3.000000,71.000000

In [17]:
# Check for duplicates
duplicated_df = df[df.duplicated(keep=False)].sort_values("QuoteRef")
print(f"There are {duplicated_df.shape[0]} duplicated rows")
duplicated_df

There are 23 duplicated rows

,QuoteRef,Channel,Product,Smoker,Joint?,Person1 Age,Term,TotalPremium,NBC,Sold,JF (Score),WGB (No. of other addresses held),X (Months same person on ER at current address),EF (No. of people not same surname at current address),NOB (Property group),URB (Income group),LSB (Regional banded house price band),BB (Number of CCJs),ND (Months since last CCJ)
13,EGVY-50,MSM,Level with CI,Y,Y,49.0,40,43.15,1112.31,N,565,3.0,7.0,6.0,7,3,6.0,0.0,-999997.0
14,EGVY-50,MSM,Level with CI,Y,Y,49.0,40,43.15,1112.31,N,565,3.0,7.0,6.0,7,3,6.0,0.0,-999997.0
5,FBJY-71,CTM,Decreasing with CI,N,N,59.0,30,18.03,439.97,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
6,FBJY-71,CTM,Decreasing with CI,N,N,59.0,30,18.03,439.97,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
2754,GUZK-85,Direct,Level,Y,Y,41.0,5,17.07,477.05,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2752,GUZK-85,Direct,Level,Y,Y,41.0,5,17.07,477.05,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2753,GUZK-85,Direct,Level,Y,Y,41.0,5,17.07,477.05,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2741,HCQF-93,Direct,Level,Y,N,36.0,30,8.59,268.45,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2740,HCQF-93,Direct,Level,Y,N,36.0,30,8.59,268.45,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2739,HCQF-93,Direct,Level,Y,N,36.0,30,8.59,268.45,N,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,KBEK-14,CTM,Decreasing accelerated,Y,Y,34.0,30,14.66,323.73,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
9,KBEK-14,CTM,Decreasing accelerated,Y,Y,34.0,30,14.66,323.73,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
10,KBEK-14,CTM,Decreasing accelerated,Y,Y,34.0,30,14.66,323.73,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
1948,OKZF-82,Direct,Level,N,Y,38.0,30,50.00,937.46,N,572,1.0,-999997.0,12.0,13,4,1.0,0.0,-999997.0
1949,OKZF-82,Direct,Level,N,Y,38.0,30,50.00,937.46,N,572,1.0,-999997.0,12.0,13,4,1.0,0.0,-999997.0
4,OZIK-66,Direct,Level with CI,N,Y,35.0,20,22.41,572.16,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
151,OZIK-66,Direct,Level with CI,N,Y,35.0,20,22.41,572.16,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
91,OZIK-66,Direct,Level with CI,N,Y,35.0,20,22.41,572.16,N,563,2.0,-999997.0,2.0,17,5,3.0,0.0,-999997.0
2748,UUIP-39,CTM,Level,N,Y,45.0,20,31.52,634.58,N,589,0.0,157.0,3.0,14,4,5.0,0.0,-999997.0
2749,UUIP-39,CTM,Level,N,Y,45.0,20,31.52,634.58,N,589,0.0,157.0,3.0,14,4,5.0,0.0,-999997.0
50,YITT-76,MSM,Level,N,Y,39.0,20,16.53,418.15,Y,580,1.0,60.0,3.0,9,3,1.0,0.0,-999997.0
49,YITT-76,MSM,Level,N,Y,39.0,20,16.53,418.15,Y,580,1.0,60.0,3.0,9,3,1.0,0.0,-999997.0
48,YITT-76,MSM,Level,N,Y,39.0,20,16.53,418.15,Y,580,1.0,60.0,3.0,9,3,1.0,0.0,-999997.0

Duplicates don't show any obvious patterns. I assume they are data entry errors so will drop them.

In [18]:
# Removing duplicates
print("Length of raw df: ", len(df))
df = df.drop_duplicates()
print("Length of df after dropping duplicates: ", len(df))

Length of raw df:  2758
Length of df after dropping duplicates:  2744

Using the Sweetviz package to run quick but comprhensive data visualisations.

In [19]:
# Running intial sweetviz report
initial_report = sv.analyze(df)
initial_report.show_html("Sweetviz Reports/InitialReport.html")

                                             |          | [  0%]   00:00 -> (? left)

Report Sweetviz Reports/InitialReport.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

### Issues:
- Data mis-matches
- Missing values (left at things like 999 etc)
- Categorical varibales that may be ordinal

In [20]:
def clean_df(df):
    """
    Replaces specific outlier/'fake-missings' values with NaN
    """

    # Dictionary mapping each column to a list of values to replace with NaN
    column_replacements = {
        "JF (Score)": [9999],
        "X (Months same person on ER at current address)": [-999997],
        "EF (No. of people not same surname at current address)": [-999997],
        "ND (Months since last CCJ)": [-999997],
        "NOB (Property group)": ["{ND}", "XX"],
        "URB (Income group)": ["{ND}", "X"],
        "LSB (Regional banded house price band)": [99, -999997],
        "BB (Number of CCJs)": [-999997],
    }

    # Apply replacements only to the specified columns
    for col, outlier_values in column_replacements.items():
        if col in df.columns:
            df[col].replace(outlier_values, np.nan, inplace=True)

    # Enforcing binary columns
    binary_feats = ["Smoker", "Joint?", "Sold"]
    yes_no_map = {"Yes": "Y", "No": "N"}
    binary_map = {"Y": 1, "N": 0}

    for feat in binary_feats:
        df[feat] = df[feat].map(yes_no_map).fillna(df[feat])
        df[feat] = df[feat].map(binary_map).fillna(df[feat])

    
    return df

df_cleaned = clean_df(df)

C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace(outlier_values, np.nan, inplace=True)
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col].replace(outlier_values, np.nan, inplace=True)
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feat] = df[feat].map(yes_no_map).fillna(df[feat])
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:30: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[feat] = df[feat].map(binary_map).fillna(df[feat])
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feat] = df[feat].map(binary_map).fillna(df[feat])
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feat] = df[feat].map(yes_no_map).fillna(df[feat])
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feat] = df[feat].map(binary_map).fillna(df[feat])
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feat] = df[feat].map(yes_no_map).fillna(df[feat])
C:\Users\Store\AppData\Local\Temp\ipykernel_13604\399518874.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feat] = df[feat].map(binary_map).fillna(df[feat])

In [21]:
# Run another report to check the changes have worked
CleanedReport = sv.analyze(df_cleaned)
CleanedReport.show_html("Sweetviz Reports\CleanedReport.html")

                                             |          | [  0%]   00:00 -> (? left)

Report Sweetviz Reports\CleanedReport.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [22]:

# Save the clean df
df_cleaned.to_csv("Data\MockDataSet1_Cleaned.csv", index=False)